services:
  - type: web
    name: beatsync-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PUBLIC_SERVER_URL
        value: https://beatsync-server-i9tn.onrender.com
